eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: telegram-bot-dispatcher
server:
  port: 443
  ssl:
    key-store: /*** path to keystore ***/keystore.p12
    key-store-password: *** your password ***
    key-store-type: PKCS12
    key-alias: telegram-bot